### ISSUE TITLE
'font-family: unset' Microsoft Outlook Issue 

### ISSUE THREAD

**Issue by philbishff** [bootstrap-email/bootstrap-email#106] opened 2021-04-07 09:55 UTC
Hello,
I use Bootstrap Mail for a year now in a client project. For compilation I use the online editor. I recompiled my templates a few weeks ago and the client told me, that mails now have a serif font. The client uses Microsoft Outlook on Windows. I identified the following snippet of code
`body,td,input,textarea,select{margin:unset;font-family:unset}`
in the <style>-tag, that is responsible for this behavior, especially the `font-family:unset` of course.
This code snippet wasn't included in the previous versions of my mail templates I built with Bootstrap Mail online editor.
Why was this snippet added?

**Comment by stuyam** [comment] 2021-05-08 23:30
Try using v1 and not v0 in the online editor. Let me know if that works, else I can figure something else out. That was added from this PR and seemed to have cause more issues: https://github.com/bootstrap-email/bootstrap-email/pull/43

It is reverted in the v1 version though.

**Comment by stuyam** [comment] 2021-05-08 23:32
Duplicate of #57

**Comment by stuyam** [comment] 2021-09-17 01:49
Fixed in [v1](https://github.com/bootstrap-email/bootstrap-email/releases/tag/1.0.0)

**Closed by stuyam** 2021-09-17 01:49 UTC
Labels: duplicate, v0
