### ISSUE TITLE
command line tool to compile emails

### ISSUE THREAD

**Issue by AmirSasson** [bootstrap-email/bootstrap-email#34] opened 2019-08-05 05:57 UTC
How can I use this great project in command line in my CI?
I would like to keep in my source control only the "raw" htmls emails, and during the CI "compile" the templates (using this great project capabilities), and push to my provider the "compiled" templates.
anyway ideas how can I do this?

**Comment by sebitoelcheater** [comment] 2019-08-21 14:33
+1. Such a project makes no sense to restrict this to Rails.

**Comment by stuyam** [comment] 2019-08-21 14:58
Restricted to rails because I don't know how else to make it 😂happy for contributions to make it a cli utility!

**Comment by stuyam** [comment] 2020-10-18 19:30
Coming soon...

**Comment by ComtelJeremy** [comment] 2020-11-19 07:19
We have been watching with interest! @stuyam We are planning our template build step around this being available. I'm sure you are a busy person, so no pressure. Just wondering if you have any rough estimate when to expect this. We a really appreciate this awesome tool!

**Comment by stuyam** [comment] 2020-11-19 22:21
@ComtelJeremy my cryptic message wasn't enough for you to determine when it will be released? 😂 Totally valid haha, not as soon as I would wish because it is undergoing a huge rebuild. But Im hoping for soon after the new year 🤞 so like 2 months. It is undergoing a massive rewrite but it also means the result will hopefully be worth the wait. 

Soon there will be Rails, Ruby, CLI, and online editor options to compile and hopefully satisfy peoples needs. The compiling engine and stylesheets are getting more features and better rendering results in email clients. As well as a whole host of prebuilt templates that I will be selling to support the project.

Lots of things to look forward to soon. Hopefully I will get an alpha or beta out sooner that people can start to use. 🎉

**Comment by ComtelJeremy** [comment] 2020-11-19 22:45
@stuyam Thanks you for the quick reply! Good to hear. 🚀 We will proceed building our system with this in mind.

We would be happy to try an alpha or beta if it helps, as long as we can drop it into our Azure build steps to test (which I'm sure we can if it is Ruby). Let us know if that would be helpful at all. We are planning to use it for our e-mail templates for our ASP.Net Core web app, using a separate git repo to store and version the templates, which automates the process (we are manually using the editor for now).

Other than an all Chinese e-mail (caused by our e-mail provider not being able to handle a unicode copyright symbol, not your library's fault in the end - Lesson: use &copy;) we have had a perfect experience using it manually so far. 🥇

**Comment by stuyam** [comment] 2020-11-20 01:51
Thanks so much for the support @ComtelJeremy, made my day! I will absolutely keep you posted 👍 

Re: email in Chinese. If you have information on how to reproduce this I would love to find out more. I need an example email that repeatably breaks to test. It would be great if there was a way we could sanitize it in a way that didn't completely break the entire email. 

If you are willing, feel free to email me at stu at my github handle dot com, I would love to pick your brain about how you will be using the CLI and get more info on the Chinese email stuff 👍

**Comment by ComtelJeremy** [comment] 2020-12-30 18:44
Hi @stuyam. Hope you and yours are well! Just checking in... I was wondering if there is an alpha version of 1.0 CLI that you wanted us to test out? We have almost finished our infrastructure project and are able to put the CLI to work soon.

**Comment by stuyam** [comment] 2020-12-31 00:31
No alpha yet, but hoping very soon. I will keep you posted, thanks for checking in. I am pushing 🙏

**Comment by ComtelJeremy** [comment] 2020-12-31 00:34
@stuyam No problem, and please do not view my message as a 👉 poke. Just letting you know we are here to test when you are ready for that. 😄

**Comment by stuyam** [comment] 2020-12-31 00:54
Absolutely @ComtelJeremy, I appreciate you 🙏

**Comment by stuyam** [comment] 2021-01-25 14:55
@ComtelJeremy a first alpha version with CLI support is finally here! https://v1.bootstrapemail.com/docs/setup Still lots of polish to do on docs and final touches but is in a pretty good state. Definitely looking for any and all feedback in your experience using the new CLI and the options it supports. 

Also be sure to check out the [What's New](https://v1.bootstrapemail.com/docs/whats-new) section of the docs to see all the new classes and changes 👍

**Comment by stuyam** [comment] 2021-09-17 01:52
Command line support is now in [v1](https://github.com/bootstrap-email/bootstrap-email/releases/tag/1.0.0)

**Closed by stuyam** 2021-09-17 01:52 UTC
Labels: v0, v1
